# Dockerfile for the front end
FROM node:20

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

#Remove the existing file if it exists
RUN rm -f src/app/configuration/config.json

#Create a new config.json file with specific content
RUN echo '{ "pages": [], "groups": [], "websocketUrl": "ws://localhost:5000", "apiUrl": "http://localhost:5000/api/topics" }' > src/app/configuration/config.json


RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
