# Dockerfile for the back end
# for raspberry pi sudo docker buildx build --platform linux/arm64,linux/amd64   -t henriwillekens/aquabots:backend-latest   --push   -f Dockerfile.backend .
FROM node:20

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

EXPOSE 5000

CMD ["node", "src/app/mqtt/mqtt_config"]
