version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: henriwillekens/aquabots:frontend-latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: henriwillekens/aquabots:backend-latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
